#!/usr/bin/env python3
"""Repo hygiene gate — what is allowed to land in the RFC repo, and nothing else.

This repo is the canonical normative artifact. Everything tracked here is
something a future RFC reader, an IETF datatracker submission, or a citation
resolves against. A file that is not needed for that has a cost and no benefit:
it enlarges the citable surface, it is one more thing to keep in parity, and
once published it cannot be quietly withdrawn.

WHY AN ALLOWLIST AND NOT A DENYLIST

    A denylist only ever catches the junk somebody already thought of. `.bak`
    files got in because nothing said they could not; the next thing gets in the
    same way. An allowlist inverts the burden — a new *kind* of file has to be
    named here, on purpose, with a reason, before it can land. The reason
    travels with the rule so a later reader knows why the category exists.

    The categories below are the answer to "is it needed for the spec?" Adding
    one is a decision. Deleting a file to satisfy this script is not.

Usage:  python3 scripts/check-repo-hygiene.py [--verbose]
Exit 1 if anything tracked falls outside the allowlist, or if a never-land
pattern is tracked at all.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Every tracked path must match exactly one of these. Category first so the
# report groups by intent rather than by directory.
ALLOWED = [
    ("generated", r"^rfcs-md/[^/]+\.md$",
     "the clean render of rfc-src/ for the GitHub Pages site — retired "
     "rfcs/ 2026-08-14 (it drifted, missing the whole Limits section, "
     "with no gate able to see an omission); mechanically generated by "
     "gen-rfcs-md.py, never hand-edited — gen-rfcs-md.py --check is the "
     "diff gate"),
    ("generated", r"^rfcs-txt/[^/]+\.txt$",
     "the five filed Internet-Drafts, generated from rfc-src/ by "
     "gen-rfc-txt.sh — the flip ran 2026-08-14; never hand-edited, and "
     "gen-rfc-txt.sh --check is the diff gate"),
    ("normative", r"^(glossary\.md|constitution\.txt)$",
     "root-level normative companions to the set"),
    ("normative", r"^catalog/[^/]+\.md$",
     "the catalogue's hand-authored halves — the index's normative rules and "
     "each domain's conventions prose (D5/#66, built by #108)"),
    ("normative", r"^specifications/[^/]+\.md$",
     "normative documents that are not RFCs in the set — the Kinetic "
     "Envelope and the deployment profile. They bind an implementation the "
     "same way rfcs/ does, so they sit beside it rather than inside a "
     "documentation directory, where a reader cannot tell a ruled document "
     "from a page describing one"),
    ("normative", r"^specifications/conformance/[^/]+\.json$",
     "the reference vectors those documents are conformed against — a "
     "conformance claim is worth exactly the vectors it names, so the "
     "vectors are part of the normative artifact and not an attachment"),

    ("source", r"^rfc-src/[^/]+\.md$",
     "kramdown-rfc source for all 27 specs (#78) — authored here once the "
     "format-spine flip runs; until then derived from rfcs-txt at HEAD by "
     "108-build-rfc-src.py, and the flip is scripts/flip-format-spine.sh"),
    ("source", r"^catalog/[^/]+\.json$",
     "the canonical form of the Context Signals catalogue — JSON is source "
     "(D5/#66); the markdown tables are generated from it"),
    ("generated", r"^catalog/generated/[^/]+\.md$",
     "catalogue tables generated from catalog/*.json by "
     "scripts/gen-catalog-tables.py — never hand-edited; "
     "gen-catalog-tables.py --check is the gate"),
    ("source", r"^schemas/[^/]+\.json$",
     "the canonical wire artifacts — the machine form of what the series "
     "requires on the wire, cited by absolute $id and validated against by "
     "implementers. They left docs/ because a documentation directory is not "
     "a place a normative artifact is published from: a reader who fetches a "
     "$id must land on the thing itself, not on a copy the site happens to "
     "mirror"),
    ("source", r"^schemas/index\.md$",
     "the reader's index over those artifacts, kept beside the JSON it lists "
     "so the listing cannot drift from the directory — the one page that has "
     "to move with the files rather than stay behind with the site"),

    ("site", r"^docs/.*\.(md|json)$",
     "mkdocs content the site mirrors; docs/ is in vocabulary scope (#64, D)"),
    ("site", r"^docs/(javascripts|stylesheets|overrides)/.*$",
     "mkdocs theme assets — needed to build, not to read the spec"),
    ("site", r"^docs/assets/.*$",
     "mkdocs images — needed to build, not to read the spec"),
    ("site", r"^docs/rfcs$",
     "symlink to ../rfcs — how mkdocs serves the spec set without a second copy"),
    ("site", r"^mkdocs\.yml$", "the site build config"),

    ("governance", r"^(LICENSE|NOTICE|CITATION\.cff|\.zenodo\.json)$",
     "licensing, attribution, and the DOI record"),
    ("governance", r"^(CONTRIBUTING|CODE_OF_CONDUCT|PROVENANCE|VERSIONING|README)\.md$",
     "how the set is contributed to, versioned, and cited"),
    ("governance", r"^SECURITY-NOTES\.md$",
     "defects found in a published tag, readable before the release that "
     "corrects them — tags never move, so this is the only place they can go"),
    ("governance", r"^CHANGELOG\.md$",
     "the normative change record, one entry per change with the finding that "
     "forced it — a MAJOR release is a promise about what broke, and the "
     "promise has to be written down somewhere a citation resolves against"),
    ("governance", r"^MIGRATION\.md$",
     "what an implementer pinned to the previous release has to change, split "
     "wire-format break from prose change — the set breaks deliberately and "
     "ships no dual-accept machinery, so this document is the migration path"),
    ("governance", r"^RELEASE-NOTES-v[0-9]+\.[0-9]+\.[0-9]+\.md$",
     "the account of why a release exists, which the tag's own notes are "
     "drawn from — versioned in the filename because a published release's "
     "notes are not rewritten by the next one"),

    ("tooling", r"^scripts/[^/]+\.(py|sh)$",
     "the executable success criteria — checkable or they are aspirations"),
    ("tooling", r"^\.github/(workflows|ISSUE_TEMPLATE)/.*$",
     "CI and issue templates"),
    ("tooling", r"^\.github/PULL_REQUEST_TEMPLATE\.md$", "PR template"),
    ("tooling", r"^\.gitignore$", "the first half of this gate"),
]

# These never land, whatever else is true. A file matching one of these is not
# a category question — it is an accident that got committed.
NEVER = [
    (r"\.bak$", "editor backup — a .bak is never the authoritative copy"),
    (r"~$", "editor backup"),
    (r"\.sw[op]$", "vim swap file"),
    (r"(^|/)\.DS_Store$", "macOS directory metadata"),
    (r"(^|/)__pycache__/", "Python bytecode"),
    (r"\.py[cod]$", "Python bytecode"),
    (r"^(venv|env|ENV)/", "a virtualenv belongs to a machine, not to a repo"),
    (r"^site/", "mkdocs build output — regenerated, never authored"),
    (r"(^|/)node_modules/", "dependency tree"),
    (r"\.(log|tmp)$", "transient output"),
]


def tracked():
    out = subprocess.run(["git", "-C", HERE, "ls-files"],
                         capture_output=True, text=True, check=True)
    return [p for p in out.stdout.splitlines() if p]


def audit(paths):
    never, unlisted, ok = [], [], {}
    for p in paths:
        hit = next((why for pat, why in NEVER if re.search(pat, p)), None)
        if hit:
            never.append((p, hit))
            continue
        cat = next((c for c, pat, _ in ALLOWED if re.match(pat, p)), None)
        if cat:
            ok.setdefault(cat, []).append(p)
        else:
            unlisted.append(p)
    return never, unlisted, ok


# A capitalised MUST in a document that never invoked BCP 14 is not a MUST — it
# is a capitalised English word. Success criterion 3 ("every normative MUST in
# the release is checkable") could not be evaluated against eight documents
# because a MISSING paragraph is invisible to a term-frequency checker: it reads
# zero and looks clean. Same blind spot #40 recorded for the D1a symbol scheme.
#
# Measured at the time this rule was written (tracker#60, 2026-08-13): eight
# rfc-src documents carried 132 normative keywords between them and none of the
# BCP 14 paragraph. The largest was ktp-conformance at 47 — the document success
# criterion 3 is evaluated THROUGH.
#
# Exemption is by NAME, never by silence. Demoting a document to informative to
# dodge this check is then a visible edit to this list rather than the absence of
# one, which is the whole point of the allowlist above applied one layer in.
KEYWORD_RE = re.compile(
    r"\b(MUST NOT|MUST|SHALL NOT|SHALL|SHOULD NOT|SHOULD|REQUIRED)\b")
BOILERPLATE = "interpreted as described in BCP 14"

INFORMATIVE = {
    # document           why it carries no normative force
    "ktp-migration": "deployment guidance and starting values; zero normative "
                     "keywords, and Section 5.1.1's role table is explicitly "
                     "informative (tracker#70)",
}


def bcp14(root):
    """Every source document with normative keywords must invoke BCP 14."""
    src = os.path.join(root, "rfc-src")
    missing, exempt = [], []
    for fn in sorted(os.listdir(src)):
        if not fn.endswith(".md"):
            continue
        name = fn[:-3]
        text = open(os.path.join(src, fn), encoding="utf-8").read()
        n = len(KEYWORD_RE.findall(text))
        if name in INFORMATIVE:
            exempt.append((name, n, INFORMATIVE[name]))
            continue
        if n and BOILERPLATE not in text:
            missing.append((name, n))
    return missing, exempt


def main():
    verbose = "--verbose" in sys.argv
    paths = tracked()
    never, unlisted, ok = audit(paths)
    missing, exempt = bcp14(HERE)

    print("Repo hygiene — only what a future RFC reader needs\n")
    print(f"{'category':<14}{'files':>7}   what it is for")
    print("-" * 92)
    for cat in ("normative", "source", "generated", "site", "governance", "tooling"):
        reasons = [why for c, _, why in ALLOWED if c == cat]
        print(f"{cat:<14}{len(ok.get(cat, [])):>7}   {reasons[0][:60]}")
    print()

    if never:
        print("MUST NOT BE TRACKED — these are accidents, not decisions:")
        for p, why in never:
            print(f"  {p:<52} {why}")
        print()

    if unlisted:
        print("NOT IN ANY CATEGORY — either it belongs and the allowlist needs a")
        print("new entry with a reason, or it does not belong and should go:")
        for p in unlisted:
            print(f"  {p}")
        print()

    if missing:
        print("NORMATIVE KEYWORDS WITHOUT BCP 14 — a capitalised MUST in a")
        print("document that never invoked BCP 14 is not yet a MUST. Add the")
        print("Requirements Language paragraph, or name the document in")
        print("INFORMATIVE above with the reason:")
        for name, n in missing:
            print(f"  rfc-src/{name}.md{'':<{max(0, 24 - len(name))}} "
                  f"{n:>3} keyword(s), no boilerplate")
        print()

    if verbose:
        for cat in ("normative", "source", "generated", "site", "governance", "tooling"):
            print(f"\n--- {cat} ({len(ok.get(cat, []))})")
            for p in ok.get(cat, []):
                print(f"  {p}")
        if exempt:
            print("\n--- informative by declaration")
            for name, n, why in exempt:
                print(f"  {name} ({n} keyword(s)) — {why}")

    total = len(never) + len(unlisted) + len(missing)
    print(f"[{len(paths)} tracked · {len(never)} must-not-be-tracked · "
          f"{len(unlisted)} uncategorised · {len(missing)} without BCP 14 · "
          f"{len(exempt)} informative by declaration]")
    return 1 if total else 0


if __name__ == "__main__":
    sys.exit(main())
